resources:
- repo: self
queue:
  name: Hosted VS2017
steps:
- powershell: ./ '.\DoTests.ps1'
  displayName: 'PowerShell Script'

- task: ArchiveFiles@2
  displayName: 'Archive $(Build.BinariesDirectory)'

trigger:
  paths:
    exclude:
    - README.md