id: calculate_severity_-_3rd-party_integrations
version: 1
contentitemexportablefields:
  contentitemfields:
    packID: CommonPlaybooks
    packName: Common Playbooks
    itemVersion: 2.2.1
    fromServerVersion: 5.0.0
    toServerVersion: ""
    definitionid: ""
vcShouldKeepItemLegacyProdMachine: false
name: Calculate Severity - 3rd-party integrations
description: Calculates the incident severity level according to the methodology of
  a 3rd-party integration.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 3eded69b-617e-4212-86b7-2537474285f3
    type: start
    task:
      id: 3eded69b-617e-4212-86b7-2537474285f3
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "25"
      - "26"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1032.5,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: 5f92bc72-085f-4c03-8404-82f83dac6c62
    type: regular
    task:
      id: 5f92bc72-085f-4c03-8404-82f83dac6c62
      version: -1
      name: Set severity to "High"
      description: Set the severity level to High.
      scriptName: Set
      type: regular
      iscommand: false
      brand: Builtin
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      key:
        simple: Severity
      value:
        simple: high
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 507.5,
          "y": 730
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "10":
    id: "10"
    taskid: 483350d5-ab17-44cd-87b3-0e2360ce3577
    type: title
    task:
      id: 483350d5-ab17-44cd-87b3-0e2360ce3577
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1032.5,
          "y": 1004
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "21":
    id: "21"
    taskid: a91ad8e7-d063-4466-8137-711519c902f2
    type: condition
    task:
      id: a91ad8e7-d063-4466-8137-711519c902f2
      version: -1
      name: Is there a Qualys severity?
      description: Check if there is a “QualysSeverity” in the playbook inputs.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "10"
      "yes":
      - "22"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: inputs.QualysSeverity
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1247.5,
          "y": 340
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "22":
    id: "22"
    taskid: 52fae7c2-b907-4877-8a6a-ed1fbf0ad988
    type: condition
    task:
      id: 52fae7c2-b907-4877-8a6a-ed1fbf0ad988
      version: -1
      name: Assign severity level based on Qualys vulnerability score
      description: |-
        Severity level is assigned according to:

        * High = 4+
        * Medium = 2-3
        * Low = 1
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      HIGH:
      - "6"
      LOW:
      - "24"
      MEDIUM:
      - "23"
    separatecontext: false
    conditions:
    - label: HIGH
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: inputs.QualysSeverity
                filters:
                - - operator: greaterThanOrEqual
                    left:
                      value:
                        simple: inputs.QualysSeverity
                      iscontext: true
                    right:
                      value:
                        simple: "4"
            iscontext: true
    - label: MEDIUM
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: inputs.QualysSeverity
                filters:
                - - operator: greaterThanOrEqual
                    left:
                      value:
                        simple: inputs.QualysSeverity
                      iscontext: true
                    right:
                      value:
                        simple: "2"
                - - operator: lessThan
                    left:
                      value:
                        simple: inputs.QualysSeverity
                      iscontext: true
                    right:
                      value:
                        simple: "4"
            iscontext: true
    - label: LOW
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: inputs.QualysSeverity
                filters:
                - - operator: lessThan
                    left:
                      value:
                        simple: inputs.QualysSeverity
                      iscontext: true
                    right:
                      value:
                        simple: "2"
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1247.5,
          "y": 513
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "23":
    id: "23"
    taskid: 89c78898-8fef-4807-8a3d-1c4f042c4eb2
    type: regular
    task:
      id: 89c78898-8fef-4807-8a3d-1c4f042c4eb2
      version: -1
      name: Set severity to "Medium"
      description: Set the severity level to Medium.
      scriptName: Set
      type: regular
      iscommand: false
      brand: Builtin
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      key:
        simple: Severity
      value:
        simple: medium
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1032.5,
          "y": 730
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "24":
    id: "24"
    taskid: 84f71501-bcb9-481c-85d5-2efa59f1c1a4
    type: regular
    task:
      id: 84f71501-bcb9-481c-85d5-2efa59f1c1a4
      version: -1
      name: Set severity to "Low"
      description: Set the severity level to Low.
      scriptName: Set
      type: regular
      iscommand: false
      brand: Builtin
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      key:
        simple: Severity
      value:
        simple: low
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1554,
          "y": 730
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "25":
    id: "25"
    taskid: 1487586f-f1f8-4136-8d7e-444a34750493
    type: title
    task:
      id: 1487586f-f1f8-4136-8d7e-444a34750493
      version: -1
      name: Calculate using Qualys Vulnerability Management
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "21"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1247.5,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "26":
    id: "26"
    taskid: aa7b1201-afbc-4d7b-89f5-e21011257699
    type: title
    task:
      id: aa7b1201-afbc-4d7b-89f5-e21011257699
      version: -1
      name: Calculate using Nexpose Vulnerability Management
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "27"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 817.5,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "27":
    id: "27"
    taskid: 9712ee01-9cb9-4dfa-80b3-aa3beadf990c
    type: condition
    task:
      id: 9712ee01-9cb9-4dfa-80b3-aa3beadf990c
      version: -1
      name: Is there a Nexpose severity?
      description: Check if there is a “NexposeSeverity” in the playbook inputs.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "10"
      "yes":
      - "28"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: inputs.NexposeSeverity
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 817.5,
          "y": 340
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "28":
    id: "28"
    taskid: d5f43287-75c2-4799-8374-95677a68c876
    type: condition
    task:
      id: d5f43287-75c2-4799-8374-95677a68c876
      version: -1
      name: Assign severity level based on Nexpose vulnerability score
      description: |-
        Severity level is assigned according to:

        * High = Critical
        * Medium = Severe
        * Low = Moderate
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      HIGH:
      - "6"
      LOW:
      - "24"
      MEDIUM:
      - "23"
    separatecontext: false
    conditions:
    - label: HIGH
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: inputs.NexposeSeverity
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: inputs.NexposeSeverity
                      iscontext: true
                    right:
                      value:
                        simple: Critical
                    ignorecase: true
            iscontext: true
    - label: MEDIUM
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: inputs.NexposeSeverity
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: inputs.NexposeSeverity
                      iscontext: true
                    right:
                      value:
                        simple: Severe
                    ignorecase: true
            iscontext: true
    - label: LOW
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: inputs.NexposeSeverity
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: inputs.NexposeSeverity
                      iscontext: true
                    right:
                      value:
                        simple: Moderate
                    ignorecase: true
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 817.5,
          "y": 529
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
system: true
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1019,
        "width": 1426.5,
        "x": 507.5,
        "y": 50
      }
    }
  }
inputs:
- key: QualysSeverity
  value:
    complex:
      root: Qualys
      accessor: Severity
  required: false
  description: Qualys Vulnerability Severity score (1-5).
  playbookInputQuery: null
- key: NexposeSeverity
  value:
    complex:
      root: Nexpose
      accessor: Asset.Vulnerability.Severity
  required: false
  description: ' Nexpose Vulnerability Severity score (Moderate, Severe, Critical).'
  playbookInputQuery: null
outputs:
- contextPath: Severity
  description: The output severity
  type: string
