id: Get Original Email - Generic v2
version: 1
contentitemexportablefields:
  contentitemfields:
    packID: Phishing
    packName: Phishing
    itemVersion: 3.2.0
    fromServerVersion: 6.0.0
    toServerVersion: ""
    definitionid: ""
vcShouldKeepItemLegacyProdMachine: false
name: Get Original Email - Generic v2
description: |-
  This v2 playbook is used inside the phishing flow. The inputs in this version do not use labels and also allow the user to supply an email brand.
  Note: You must have the necessary permissions in your email service to execute a global search.

  To retrieve the email files directly from the email service providers, use one of the provided inputs (Agari Phishing Defense customers should also use the following):
  - EWS: eDiscovery
  - Gmail: Google Apps Domain-Wide Delegation of Authority
  - MSGraph: As described in the [message-get API](https://docs.microsoft.com/en-us/graph/api/message-get) and the [user-list-messages API](https://docs.microsoft.com/en-us/graph/api/user-list-messages)
  - EmailSecurityGateway retrieves EML files from:
      * FireEye EX
      * FireEye CM
      * Proofpoint Protection Server
      * Mimecast
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 39f9f803-0a5c-48ce-852c-6b2cba1603e3
    type: start
    task:
      id: 39f9f803-0a5c-48ce-852c-6b2cba1603e3
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "13"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": -130,
          "y": -270
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: ba875fe0-ddb9-49d8-87bd-0244412ece59
    type: title
    task:
      id: ba875fe0-ddb9-49d8-87bd-0244412ece59
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": -130,
          "y": 390
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "10":
    id: "10"
    taskid: 57283e40-45d3-4750-8b23-0282b034ca1b
    type: playbook
    task:
      id: 57283e40-45d3-4750-8b23-0282b034ca1b
      version: -1
      name: Get Original Email - Microsoft Graph Mail
      description: |-
        This playbook retrieves the original email using the Microsoft Graph Mail integration.
        Note: You must have the necessary permissions in the Microsoft Graph Mail integration as described in the [message-get API](https://docs.microsoft.com/en-us/graph/api/message-get) and the [user-list-messages API](https://docs.microsoft.com/en-us/graph/api/user-list-messages).
      playbookId: Get Original Email - Microsoft Graph Mail
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      MessageID:
        complex:
          root: inputs.MessageID
      ThreadTopic:
        complex:
          root: inputs.EmailSubject
      UserID:
        complex:
          root: inputs.UserID
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": -1300,
          "y": 220
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: true
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "11":
    id: "11"
    taskid: d8997091-97e2-446d-820b-ee131a482796
    type: playbook
    task:
      id: d8997091-97e2-446d-820b-ee131a482796
      version: -1
      name: Get Original Email - EWS v2
      description: |-
        This v2 playbook retrieves the original email in a thread as an EML file (and not an email object as in the previous version) by using the EWS v2 integration.
        It also reduces the number of tasks to perform the fetch action.
        Note: You must have the necessary eDiscovery permissions in the EWS integration to execute a global search.
      playbookId: Get Original Email - EWS v2
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      MessageID:
        complex:
          root: inputs.MessageID
      TargetMailbox:
        complex:
          root: inputs.UserID
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": -820,
          "y": 220
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: true
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "12":
    id: "12"
    taskid: 5481e887-03ee-44b2-8f26-411c0420cd3a
    type: playbook
    task:
      id: 5481e887-03ee-44b2-8f26-411c0420cd3a
      version: -1
      name: Get Original Email - Gmail v2
      description: "This v2 playbook uses the reporter's email headers to retrieve
        the original email, which helps reduce the number of tasks to retrieve the
        original email. \nUse this playbook to retrieve the original email using the
        Gmail integration, including headers and attachments.\nNote: You must have
        the necessary Google Apps Domain-Wide Delegation of Authority permissions
        in your Gmail service to execute global search.\n"
      playbookId: Get Original Email - Gmail v2
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      MessageID:
        complex:
          root: inputs.MessageID
      UserID:
        complex:
          root: inputs.UserID
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": -340,
          "y": 220
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "13":
    id: "13"
    taskid: 3b8ffc22-29ed-4a57-84ff-8aed798de414
    type: condition
    task:
      id: 3b8ffc22-29ed-4a57-84ff-8aed798de414
      version: -1
      name: Check EmailBrand
      description: Check if "EmailBrand" has a valid value.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "14"
      EWS:
      - "11"
      Email Security:
      - "15"
      Gmail:
      - "12"
      MSGraph:
      - "10"
    separatecontext: false
    conditions:
    - label: Gmail
      condition:
      - - operator: isEqualString
          left:
            value:
              complex:
                root: inputs.EmailBrand
            iscontext: true
          right:
            value:
              simple: Gmail
    - label: EWS
      condition:
      - - operator: isEqualString
          left:
            value:
              complex:
                root: inputs.EmailBrand
            iscontext: true
          right:
            value:
              simple: EWS v2
        - operator: isEqualString
          left:
            value:
              complex:
                root: inputs.EmailBrand
            iscontext: true
          right:
            value:
              simple: EWSO365
    - label: MSGraph
      condition:
      - - operator: isEqualString
          left:
            value:
              complex:
                root: inputs.EmailBrand
            iscontext: true
          right:
            value:
              simple: MicrosoftGraphMail
    - label: Email Security
      condition:
      - - operator: isEqualString
          left:
            value:
              complex:
                root: inputs.EmailBrand
            iscontext: true
          right:
            value:
              simple: EmailSecurityGateway
          ignorecase: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": -130,
          "y": -120
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "14":
    id: "14"
    taskid: e271a14b-f855-4fa9-8ed6-cc99faeff175
    type: title
    task:
      id: e271a14b-f855-4fa9-8ed6-cc99faeff175
      version: -1
      name: No brand - run all
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "10"
      - "11"
      - "12"
      - "15"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": -130,
          "y": 70
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "15":
    id: "15"
    taskid: 2b98d9b9-44b1-42e2-8efa-38d45dc2376a
    type: playbook
    task:
      id: 2b98d9b9-44b1-42e2-8efa-38d45dc2376a
      version: -1
      name: Get Email From Email Gateway - Generic
      playbookName: Get Email From Email Gateway - Generic
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      MessageID:
        complex:
          root: inputs.MessageID
      UserID:
        complex:
          root: inputs.UserID
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 0
    view: |-
      {
        "position": {
          "x": 320,
          "y": 220
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: true
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
system: true
view: |-
  {
    "linkLabelsPosition": {
      "13_10_MSGraph": 0.9,
      "13_11_EWS": 0.9,
      "13_12_Gmail": 0.85,
      "13_15_Email Security": 0.9
    },
    "paper": {
      "dimensions": {
        "height": 725,
        "width": 2000,
        "x": -1300,
        "y": -270
      }
    }
  }
inputs:
- key: MessageID
  value: {}
  required: false
  description: The original email message ID to retrieve. This should hold the value
    of the "Message-ID" header of the original email.
  playbookInputQuery: null
- key: UserID
  value: {}
  required: false
  description: The email address of the user to fetch the original email for. For
    Gmail, the authenticated user.
  playbookInputQuery: null
- key: EmailSubject
  value: {}
  required: false
  description: The original email subject.
  playbookInputQuery: null
- key: EmailBrand
  value: {}
  required: false
  description: |-
    If this value is provided, only the relevant playbook runs. If no value is provided, all sub-playbooks are run.
    Possible values:
    - Gmail
    - EWS v2
    - EWSO365
    - MicrosoftGraphMail
    - EmailSecurityGateway

    Choosing EmailSecurityGateway executes the following if enabled:
        - FireEye EX (Email Security)
        - Proofpoint TAP
        - Mimecast
  playbookInputQuery: null
outputs:
- contextPath: Email
  description: The email object.
  type: string
- contextPath: File
  description: The original email attachments.
  type: string
- contextPath: Email.To
  description: The email recipient.
  type: string
- contextPath: Email.From
  description: The email sender.
  type: string
- contextPath: Email.CC
  description: The CC address of the email.
  type: string
- contextPath: Email.BCC
  description: The BCC address of the email.
  type: string
- contextPath: Email.HTML
  description: The email HTML.
  type: string
- contextPath: Email.Body
  description: The email text body.
  type: string
- contextPath: Email.Headers
  description: The email headers.
  type: string
- contextPath: Email.Subject
  description: The email subject.
  type: string
- contextPath: Email.HeadersMap
  description: The email headers map.
  type: string
- contextPath: reportedemailentryid
  description: If the original EML was retrieved, this field holds the file's Entry
    ID.
  type: string
